### ISSUE TITLE
Valore di ritorno superfluo

### ISSUE THREAD

**Issue by emaborsa** [squeeze69/codicefiscale#1]
Riguardo i valori di ritorno:

    ok, err := codicefiscale.CodiceFiscale("ABCDEF12B23P432P")

Leggendo il codice e anche ció che mi dice il compilatore, le combinazioni `true, *err` e `false, nil` non possono mai avvenire. Perció sono del parere che `ok` sia superfluo e che come valore di ritorno basterebbe `err`. Se questo é `nil` é implicito che il codice fiscale sia corretto/valido.

**Comment by squeeze69** [comment]
Salve, osservazione corretta, grazie.

Sono rimasto su una prassi consolidata in GO di restituire almeno un valore ed un errore (se previsto un errore, ovvio), ma rimuoverlo non credo dia un impatto positivo sulle prestazioni (anche se è da valutare in maniera oggettiva), mentre creerebbe qualche problema a chi già lo usa, se non si vuole usare uno o l'altro valore basta usare la forma:

if _,err := codicefiscale("ABC...."); err.(*CFError) == nil {
  fmt.Println("buono");
} else {
 fmt.Println("cattivo");
}

if risultato,_ := codicefiscale("ABC....");  risultato {
  fmt.Println("buono");
} else {
 fmt.Println("cattivo");
}

Vedi i test, ad esempio.

Spiacente, ma non viene modifcato,
oppure:
